In [6]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import plotly.express as px # plotly express
%matplotlib inline 
import matplotlib.pyplot as plt
from matplotlib.pyplot import cm
import matplotlib.ticker as ticker
import matplotlib.animation as animation
from IPython.display import HTML
import pycountry
from geopy.geocoders import Nominatim
import json
import requests
# Input data files are available in the "../input/" directory.

import os
file_input=['/kaggle/input','../../../datasets/extracts/']
files={}
for dirname, _, filenames in os.walk(file_input[1]):
    for filename in filenames:
        files[filename.replace('.csv','')]=os.path.join(dirname, filename)
        print(filename.replace('.csv',''))

# Any results you write to the current directory are saved as output.

.DS_Store
covid19_italy_region
covid19_italy_province
covid_19_india
ICMRTestingDetails
HospitalBedsIndia
AgeGroupDetails
StatewiseTestingDetails
ICMRTestingLabs
population_india_census2011
IndividualDetails
countryLockdowndatesJHUMatch
countryLockdowndates
COVID19_open_line_list
time_series_covid_19_confirmed_US
time_series_covid_19_recovered
time_series_covid_19_deaths_US
covid_19_data
COVID19_line_list_data
time_series_covid_19_deaths
time_series_covid_19_confirmed

In [7]:
urls={'VA':["https://api.weather.com/v1/location/KLYH:9:US/observations/historical.json?apiKey=6532d6454b8aa370768e63d6ba5a832e&units=e&startDate=20200301&endDate=20200331",
           'https://api.weather.com/v1/location/KLYH:9:US/observations/historical.json?apiKey=6532d6454b8aa370768e63d6ba5a832e&units=e&startDate=20200401&endDate=20200430'],
     'NY':['https://api.weather.com/v1/location/KLGA:9:US/observations/historical.json?apiKey=6532d6454b8aa370768e63d6ba5a832e&units=e&startDate=20200201&endDate=20200229',
          'https://api.weather.com/v1/location/KLGA:9:US/observations/historical.json?apiKey=6532d6454b8aa370768e63d6ba5a832e&units=e&startDate=20200301&endDate=20200331',
          'https://api.weather.com/v1/location/KLGA:9:US/observations/historical.json?apiKey=6532d6454b8aa370768e63d6ba5a832e&units=e&startDate=20200401&endDate=20200430']}

In [15]:
city_keys={'Tasmania':'YMHB:9:AU',
           'New York':'KLGA:9:US',
           'Virginia':'KLYH:9:US',
           'Quebec':'CYQB:9:CA',
           'New South Wales':'YCBA:9:AU',
           'Henan':'ZHCC:9:CN',
           'Bermuda':'TXKF:9:BM',
           'Reunion':'FMEE:9:RE',
           'Lombardia':'LIML:9:IT',
           'Maharashtra':'VABB:9:IN'}

In [16]:
for keys in city_keys.items():
    df=pd.DataFrame()
    for month in pd.date_range(start='20200101',end='20200601',freq='M'):
        start,end=month.replace(day=1).strftime('%Y%m%d'),month.strftime('%Y%m%d')
        url="https://api.weather.com/v1/location/"+keys[1]+"/observations/historical.json?apiKey=6532d6454b8aa370768e63d6ba5a832e&units=e&startDate="+start+"&endDate="+end        
        res = requests.get(url)
        json_text=json.loads(res.text)
        df=pd.concat([df,pd.DataFrame(json_text['observations'])])
    df.to_csv('../../../datasets/created/weather/Weather '+keys[0]+'.csv',index=False) 
    print(keys[0])

Tasmania
New York
Virginia
Quebec
New South Wales
Henan
Bermuda
Reunion
Lombardia
Maharashtra

In [69]:
url = urls['NY'][2]
res = requests.get(url)

In [70]:
json_text=json.loads(res.text)
pd.DataFrame(json_text['observations']).head()

,key,class,expire_time_gmt,obs_id,obs_name,valid_time_gmt,day_ind,temp,wx_icon,icon_extd,...,clds,water_temp,primary_wave_period,primary_wave_height,primary_swell_period,primary_swell_height,primary_swell_direction,secondary_swell_period,secondary_swell_height,secondary_swell_direction
0,KLGA,observation,1585723860,KLGA,New York/LaGuardia,1585716660,N,42,26,2600,...,OVC,None,None,None,None,None,None,None,None,None
1,KLGA,observation,1585726080,KLGA,New York/Laguardia,1585718880,N,42,26,2600,...,OVC,None,None,None,None,None,None,None,None,None
2,KLGA,observation,1585727460,KLGA,New York/Laguardia,1585720260,N,42,26,2600,...,OVC,None,None,None,None,None,None,None,None,None
3,KLGA,observation,1585729380,KLGA,New York/Laguardia,1585722180,N,41,26,2600,...,OVC,None,None,None,None,None,None,None,None,None
4,KLGA,observation,1585731060,KLGA,New York/Laguardia,1585723860,N,41,26,2600,...,OVC,None,None,None,None,None,None,None,None,None

In [67]:
pd.DataFrame(json_text['observations']).to_csv('../../../datasets/created/weather/New-York-NY-Mar-2020.csv',index=False)

In [98]:
pd.read_csv(files['covid19_italy_province'])
# df[df['4/26/20']==df['4/26/20'].max()]
# df[df['Country/Region']!='US'].groupby(['Province/State','Country/Region']).last().sort_values('Confirmed').tail(50)
# df

,SNo,Date,Country,RegionCode,RegionName,ProvinceCode,ProvinceName,ProvinceAbbreviation,Latitude,Longitude,TotalPositiveCases
0,0,2020-02-24T18:00:00,ITA,13,Abruzzo,69,Chieti,CH,42.351032,14.167546,0
1,1,2020-02-24T18:00:00,ITA,13,Abruzzo,66,L'Aquila,AQ,42.351222,13.398438,0
2,2,2020-02-24T18:00:00,ITA,13,Abruzzo,68,Pescara,PE,42.464584,14.213648,0
3,3,2020-02-24T18:00:00,ITA,13,Abruzzo,67,Teramo,TE,42.658918,13.704400,0
4,4,2020-02-24T18:00:00,ITA,13,Abruzzo,979,In fase di definizione/aggiornamento,NaN,0.000000,0.000000,0
...,...,...,...,...,...,...,...,...,...,...,...
8699,8699,2020-05-01T17:00:00,ITA,5,Veneto,26,Treviso,TV,45.667546,12.245074,2518
8700,8700,2020-05-01T17:00:00,ITA,5,Veneto,27,Venezia,VE,45.434905,12.338452,2471
8701,8701,2020-05-01T17:00:00,ITA,5,Veneto,23,Verona,VR,45.438390,10.993527,4709
8702,8702,2020-05-01T17:00:00,ITA,5,Veneto,24,Vicenza,VI,45.547497,11.545971,2680
8703,8703,2020-05-01T17:00:00,ITA,5,Veneto,999,In fase di definizione/aggiornamento,NaN,0.000000,0.000000,317

In [105]:
df=pd.read_csv(files['covid_19_india'])
# df.sort_values('TotalPositiveCases')
df.sort_values('Confirmed')

,Sno,Date,Time,State/UnionTerritory,ConfirmedIndianNational,ConfirmedForeignNational,Cured,Deaths,Confirmed
1080,1081,18/04/20,5:00 PM,Nagaland#,-,-,0,0,0
1047,1048,17/04/20,5:00 PM,Nagaland#,-,-,0,0,0
1113,1114,19/04/20,5:00 PM,Nagaland#,-,-,0,0,0
1014,1015,16/04/20,5:00 PM,Nagaland#,-,-,0,0,0
1179,1180,21/04/20,5:00 PM,Nagaland,-,-,0,0,0
...,...,...,...,...,...,...,...,...,...
1400,1401,28/04/20,5:00 PM,Maharashtra,-,-,1282,369,8590
1432,1433,29/04/20,5:00 PM,Maharashtra,-,-,1388,400,9318
1464,1465,30/04/20,5:00 PM,Maharashtra,-,-,1593,432,9915
1496,1497,01/05/20,5:00 PM,Maharashtra,-,-,1773,459,10498
1528,1529,02/05/20,5:00 PM,Maharashtra,-,-,1879,485,11506

In [102]:
df.groupby('RegionName').last()

,SNo,Date,Country,RegionCode,Latitude,Longitude,HospitalizedPatients,IntensiveCarePatients,TotalHospitalizedPatients,HomeConfinement,CurrentPositiveCases,NewPositiveCases,Recovered,Deaths,TotalPositiveCases,TestsPerformed
RegionName,,,,,,,,,,,,,,,,
Abruzzo,1407,2020-05-01T17:00:00,ITA,13,42.351222,13.398438,297,16,313,1598,1911,18,713,324,2948,29024.0
Basilicata,1408,2020-05-01T17:00:00,ITA,17,40.639471,15.805148,49,4,53,140,193,11,160,25,378,13269.0
Calabria,1410,2020-05-01T17:00:00,ITA,18,38.905976,16.594402,105,3,108,619,727,4,299,86,1112,35101.0
Campania,1411,2020-05-01T17:00:00,ITA,15,40.839566,14.250850,478,29,507,2246,2753,21,1332,359,4444,44975.0
Emilia-Romagna,1412,2020-05-01T17:00:00,ITA,8,44.494367,11.341721,2112,197,2309,7175,9484,208,12581,3579,25644,125636.0
Friuli Venezia Giulia,1413,2020-05-01T17:00:00,ITA,6,45.649435,13.768136,131,6,137,978,1115,16,1632,294,3041,45566.0
Lazio,1414,2020-05-01T17:00:00,ITA,12,41.892770,12.483667,1372,105,1477,2969,4446,56,1744,482,6672,111988.0
Liguria,1415,2020-05-01T17:00:00,ITA,7,44.411493,8.932699,666,68,734,2784,3518,133,3424,1184,8126,32794.0
Lombardia,1416,2020-05-01T17:00:00,ITA,3,45.466794,9.190347,6628,563,7191,29282,36473,737,26136,13860,76469,236822.0
Marche,1417,2020-05-01T17:00:00,ITA,11,43.616760,13.518875,413,44,457,2754,3211,28,2153,911,6275,40123.0
Molise,1418,2020-05-01T17:00:00,ITA,14,41.557748,14.659161,17,1,18,172,190,2,89,21,300,6450.0
P.A. Bolzano,1409,2020-05-01T17:00:00,ITA,4,46.499335,11.356624,112,11,123,634,757,10,1493,278,2528,19705.0
P.A. Trento,1424,2020-05-01T17:00:00,ITA,4,46.068935,11.121231,146,19,165,1128,1293,16,2416,423,4132,22602.0
Piemonte,1419,2020-05-01T17:00:00,ITA,1,45.073274,7.680687,2503,181,2684,12878,15562,395,8025,3097,26684,114786.0
Puglia,1420,2020-05-01T17:00:00,ITA,16,41.125596,16.867367,428,39,467,2480,2947,27,731,421,4099,62702.0
Sardegna,1421,2020-05-01T17:00:00,ITA,20,39.215312,9.110616,84,12,96,648,744,18,452,117,1313,23442.0
Sicilia,1422,2020-05-01T17:00:00,ITA,19,38.115697,13.362357,399,30,429,1742,2171,28,786,237,3194,77490.0
Toscana,1423,2020-05-01T17:00:00,ITA,9,43.769231,11.255889,520,124,644,4729,5373,93,3218,854,9445,111349.0
Umbria,1425,2020-05-01T17:00:00,ITA,10,43.106758,12.388247,60,13,73,131,204,1,1121,68,1393,26285.0
Valle d'Aosta,1426,2020-05-01T17:00:00,ITA,2,45.737503,7.320149,72,3,75,17,92,5,904,137,1133,5818.0
Veneto,1427,2020-05-01T17:00:00,ITA,5,45.434905,12.338452,977,110,1087,6692,7779,138,8840,1479,18098,212706.0